### ISSUE TITLE
declara tus variables en una sola linea

### ISSUE THREAD

**Issue by nopestack** [Nestyko/Ejercicios-estadistica-de-practica-js#1]
Man seria bueno que acomodaras un poco tu javascript
Las variables se pueden declarar asi:

```
var variable1, variable2, variable3, variable4;
```

Tambien si hay varias que tienen el mismo valor  puedes igualarlas asi:

```
var variable1 = variable2 = variable3 = variable4 = 0;
```

Otra cosa para usar bootstrap tienes que cargar JQuery tambien.

**Comment by Nestyko** [comment]
mmm intersante, no sabia que podia declarar asi las variables...
y otra cosa bootstrap usa jquery 1.1 creo, no hay poblema si lo cambio por el 2.1.4?
yo lo que hago es que le dejo el 1.1 y luego de los plugins de bootstrap le importo el jquery 2.1.4 y luego mis funciones.js

**Comment by nopestack** [comment]
Depende de la version que utilices, Bootstrap v3+ pide JQuery 1.9.1 o superior. Yo deje de preocuparme tanto mientras trabajo usando Bower que es un package manager para cosas del front-end.

[Bower](http://bower.io/)

Otra cosa, carga toda libreria al final del body de tu html y el js que tu escribas cargalo justo debajo de las librerias para que la pagina cargue mas rapido, tambien es buena idea concatenar tus archivos para optimizar tiempos de carga pero por eso no te preocupes ahorita. 

Voy a seguir revisando tus archivos ahorita.
